<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Validate OHRM Login_TestSuite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>8e7e7d8d-6291-4727-be6c-dbaa1ad6d197</testSuiteGuid>
   <testCaseLink>
      <guid>17a3815b-e330-4a05-acd0-6cb21f9bfa7b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Jenkins Integration/TC_Validate OHRM Login_Login Success_001</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8d95839f-4913-49d2-8cf0-abecc2d2d856</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7ad14ed6-4d88-4c85-9d30-a4f6af36fe9a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>059b0a2b-874f-41ee-87dd-33a043824008</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fda1b303-c2ca-40b0-84c5-34f992b843b8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Local and Global Variables/TC_Validate OHRM Login_Invalid Username_002</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>36fce5b0-2c13-4e88-8f36-82dc817e36f2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>14e51542-1a25-4ffd-b4a3-3d7c406d1c1e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Local and Global Variables/TC_Validate OHRM Login_Invalid Password_003</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a06943f0-5bfe-4e1e-ab8c-e0d668acd9e1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4a66100b-960b-4b1c-baf6-f62a24d0eff1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Test Listeners/TC_Validate OHRM Login_Missing Password_004</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>58ed4217-a395-4ad8-ae29-e0499bc101e9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Test Listeners/TC_Validate OHRM Login_Missing Username_005</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
</TestSuiteEntity>
