<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Validate OHRM Admin_Employee Search_TestSuite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient>khanvms9@gmail.com;</mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>fa112405-b602-4edb-af27-25bd0ccb8175</testSuiteGuid>
   <testCaseLink>
      <guid>77f67af2-ca8d-4d35-8070-e2fc19a384d5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Data Driven Testing/TC_Validate OHRM Admin_employee search_001</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>a380ba80-6adc-4cc0-bea0-2013f6b9ac18</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Data Driven Testing/Admin_Search_Data</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>a380ba80-6adc-4cc0-bea0-2013f6b9ac18</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>emp_username</value>
         <variableId>2dffb63d-c29c-4a64-9768-3228f29d3654</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>a380ba80-6adc-4cc0-bea0-2013f6b9ac18</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>emp_role</value>
         <variableId>856c97a9-878a-45d0-b1f2-1873b8042991</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>a380ba80-6adc-4cc0-bea0-2013f6b9ac18</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>emp_status</value>
         <variableId>5defc45d-8f27-46db-b8c2-f5412a7d5e4f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>a380ba80-6adc-4cc0-bea0-2013f6b9ac18</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>emp_name</value>
         <variableId>aa757dd4-8e23-4a23-ab37-2507e260b6d8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>a380ba80-6adc-4cc0-bea0-2013f6b9ac18</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>validation_text</value>
         <variableId>e3f26ebc-9989-4dba-b8b1-527ab81b89b1</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
